#!/usr/bin/env bash

set -e

# shellcheck source=lib/common.sh
. "${0%/*}/../../lib/common.sh"

loadAddresses

DRILLLUCKYBOX=$(dapp create src/DrillLuckyBox.sol:DrillLuckyBox $ISETTINGSREGISTRY $DRILLTAKEBACK $(seth --to-uint256 1617278770))
addAddress "DRILLLUCKYBOX" "$DRILLLUCKYBOX"
